version: '{build}'
platform:
  - x64
image: Visual Studio 2017

branches:
  only:
    - master

before_build:
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - mkdir "%APPVEYOR_BUILD_FOLDER%\Build"
 - cd "%APPVEYOR_BUILD_FOLDER%\Build"
 - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\Alimer-SDK" ..

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\Build"
  - cmake --build . --target install
after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - 7z a Alimer-SDK.7z "%APPVEYOR_BUILD_FOLDER%\Alimer-SDK"
test: off
artifacts:
  path: Alimer-SDK.7z

skip_commits:
  files:
    - .travis.yml
    - LICENSE
    - README.md
    - AUTHORS.md
