version: '{build}'
platform:
  - x64
image: Visual Studio 2017
environment:
  global:
    MONO_SETUP: mono-5.10.1.47-x64-0.msi
    ALIMER_ENABLE_ALL: ON
  matrix:
    - BUILD_SHARED_LIBS: OFF
    - BUILD_SHARED_LIBS: ON

cache:
  - "%MONO_SETUP%"
install:
  - ps: |
     if (-not (test-path "$ENV:MONO_SETUP")) {
       Start-FileDownload "https://download.mono-project.com/archive/5.10.1/windows-installer/$ENV:MONO_SETUP";
     }
     msiexec /quiet /qn /norestart /i $ENV:MONO_SETUP
before_build:
 - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
 - mkdir "%APPVEYOR_BUILD_FOLDER%\Build"
 - cd "%APPVEYOR_BUILD_FOLDER%\Build"
 - cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\Alimer-SDK" ..

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\Build"
  - cmake --build . --target install
after_build:
  - cd "%APPVEYOR_BUILD_FOLDER%"
  - 7z a Alimer-SDK.7z "%APPVEYOR_BUILD_FOLDER%\Alimer-SDK"
test: off
artifacts:
  path: Alimer-SDK.7z

branches:
  only:
    - master

skip_commits:
  files:
    - .travis.yml
    - LICENSE
    - README.md